"use strict";

const careers = [];
const blogPosts = [];
const products = [{ slug: "servra", name: "Servra", tagline: "Chat. Order. Done.", category: "AI & Automation", description: "Servra is an AI Order Agent for restaurants. It sits directly on a vendor's existing WhatsApp number and helps manage ordering conversations from the moment a customer sends a message.", status: "Live", image: "/images/products/servra/img.png", href: "/products/servra" }];
const work = [
  { slug: "servra", title: "Servra — AI Order Agent for Restaurants", category: "AI & Automation", challenge: "Restaurants managing orders over WhatsApp often miss messages, repeat the same menu questions, and lose time manually calculating totals during busy periods.", approach: "We designed Servra to sit directly on a vendor's existing WhatsApp number, so customers could keep using a channel they already trust while the repetitive parts of ordering are handled automatically.", solution: "Servra responds to customer messages, shares the menu, takes orders in natural language (including voice notes where supported), calculates totals, and notifies the vendor to confirm or reject each order.", technology: ["WhatsApp", "AI / LLM", "Automation"], outcome: "Servra is live and in use, giving restaurants a faster way to handle WhatsApp orders without requiring customers to download a new app.", image: "/images/products/servra/img.png" },
  { slug: "jo-tech-gadgets-hub", title: "JO TECH Gadgets Hub", category: "Web Development / E-Commerce", description: "A modern e-commerce platform concept built from scratch for a technology and gadgets business, including product catalogue, e-commerce functionality, and an administrative backend.", technology: [], image: "/images/products/jo-tech/img.png", liveUrl: "https://jo-tech-f4mz.vercel.app/" },
];
const team = [
  { slug: "member-1", name: "Oyindamola Abisoye", role: "Project Manager / QA Engineer", department: "Leadership", photo: "/images/team/kayleb.png", bio: "Mobile development expertise in React Native.", linkedin: "", isEarlyBuilder: false },
  { slug: "member-2", name: "John Samuel", role: "Frontend Engineer", department: "Engineering", photo: "/images/team/john.png", bio: "Software Engineer with experience building responsive web applications, backend systems, and data-driven solutions using React, Next.js, Node.js, Express, ASP.NET, MSSQL, Python, and Pandas. Passionate about building scalable applications, working with databases and data, integrating APIs, and solving real-world problems through technology.", linkedin: "", isEarlyBuilder: false },
  { slug: "member-3", name: "Badmus Qudus", role: "Backend Engineer", department: "Engineering", photo: "/images/team/badmus.png", bio: "Full-Stack Developer with strong expertise in backend development, building scalable, secure, and reliable server-side applications. Experienced in API development, database management, authentication, and system architecture, while also capable of delivering modern and responsive frontend solutions. Passionate about writing clean, efficient code and building robust systems that solve real-world problems.", linkedin: "", isEarlyBuilder: false },
  { slug: "member-4", name: "Israel yaya", role: "Frontend Developer", department: "Engineering", photo: "/images/team/Israel.png", bio: "Frontend Developer focused on building modern, responsive, and user-friendly web applications. Experienced in creating clean and interactive interfaces with a strong focus on performance, usability, and responsive design. Passionate about turning ideas and designs into seamless digital experiences", linkedin: "", isEarlyBuilder: false },
  { slug: "member-5", name: "Oyindamola Abisoye", role: "Mobile dev", department: "Engineering", photo: "/images/team/kayleb.png", bio: "Mobile development expertise in React Native.", linkedin: "", isEarlyBuilder: false },
  { slug: "member-6", name: "Oyindamola Abisoye", role: "Operations", department: "Operations", photo: "/images/team/kayleb.png", bio: "Mobile development expertise in React Native.", linkedin: "", isEarlyBuilder: false },
];
const findBySlug = (items, slug) => items.find((item) => item.slug === slug) || null;
module.exports = { careers, blogPosts, products, work, team, findBySlug };
